### ISSUE TITLE
restructure repository to comply with python package best practices

### ISSUE THREAD

**Issue by hechth** [cbib/DIMet#1]
The current repository structure should be adapted to comply with current best practices. This will make it easier to publish the package on pypi and conda.

**Comment by bdartigues** [comment]
Dear @hechth
This repository is the command line version repo. I created a specific repo from this one with all the xml tool files the test-data folder, etc. this will be the repo that i will pushed into tools-iuc.

**Comment by hechth** [comment]
@bdartigues could you be so kind and point me to the repository?

Also, this doesn't change the fact that this is not a properly structured package.
